### ISSUE TITLE
secondary development

### ISSUE THREAD

**Issue by Jupiterter** [ZhiningLiu1998/imbalanced-ensemble#15]
Hi，if i wanna realize my new undersampling idea in Bagging classifiers on the package,where should I add my undersampling strategy?   thanks !

**Comment by ZhiningLiu1998** [comment]
Hi,

Thanks for asking. 
We try to pack all sampling operations into `Sampler` objects that inherit from `BaseSampler` and `SamplerMixin`:
https://github.com/ZhiningLiu1998/imbalanced-ensemble/blob/main/imbalanced_ensemble/sampler/base.py#L36

Generally, if you want to implement a new undersampling algorithm, you need to build a new class that inherits `BaseSampler`, and implement your own sampling procedure in the `_fit_resample` function. You can refer to `RandomUnderSampler` for an [example](https://github.com/ZhiningLiu1998/imbalanced-ensemble/blob/main/imbalanced_ensemble/sampler/under_sampling/_prototype_selection/_random_under_sampler.py).

After you have done that, sampler objects can be combined with `ResampleBaggingClassifier`, which is defined at [HERE](https://github.com/ZhiningLiu1998/imbalanced-ensemble/blob/main/imbalanced_ensemble/ensemble/_bagging.py#L154)

In your new `MyBagging` class that inherits from `ResampleBaggingClassifier`, you can specify to use your own resampler by passing a resampler instance to the `base_sampler` parameter of `super.__init__()`, as I did [HERE](https://github.com/ZhiningLiu1998/imbalanced-ensemble/blob/main/imbalanced_ensemble/ensemble/under_sampling/under_bagging.py#L201) (I pass a `RandomUnderSampler` instance to this parameter):

This will affect the [`ResampleBaggingClassifier._validate_estimator()`](https://github.com/ZhiningLiu1998/imbalanced-ensemble/blob/main/imbalanced_ensemble/ensemble/_bagging.py#L229) function, where we create the actual base_estimators that are trained for ResampleBagging: they are pipelines of [`MyResampler()`, Your Base Estimator (e.g., `DecisionTreeClassifier()`)].

In the parallel training of Your Bagging model, to form a base estimator, `MyResampler.fit_resample()` will be first called to get resampled data `X_, y_`. Then the base estimator (classifier) will fit the resampled data, more details can be found in the [pipeline.py](https://github.com/ZhiningLiu1998/imbalanced-ensemble/blob/main/imbalanced_ensemble/pipeline.py) file. But generally, all you need to do is to implement the `MyResampler._fit_resample` function, create `MyBagging` with `base_resampler=MyResampler()`, and implement the `MyBagging.fit` function, then it should work.

I suggest you to refer the [`UnderBaggingClassifier`](https://github.com/ZhiningLiu1998/imbalanced-ensemble/blob/main/imbalanced_ensemble/ensemble/under_sampling/under_bagging.py#L52) for a basic example. 
If you need more advanced usage, e.g., passing additional arguments to the sampler, you can do it by passing them to the [`sampler_kwargs`](https://github.com/ZhiningLiu1998/imbalanced-ensemble/blob/main/imbalanced_ensemble/ensemble/_bagging.py#L291) option of `ResampleBaggingClassifier._fit()`.
For doing this, you can refer to my implementation of [`SMOTEBaggingClassifier`](https://github.com/ZhiningLiu1998/imbalanced-ensemble/blob/main/imbalanced_ensemble/ensemble/over_sampling/smote_bagging.py#L277), where I combine a SMOTE resampler with Bagging, and pass the `k_neighbors` parameter to SMOTE sampler using this trick.

Hope this helps.

**Comment by Jupiterter** [comment]
Thanks for your answer.
I have already accomplished my new base class MySampler.But when I implemented my new MySamplerBaggingClassifier.fit function,some errors are returned.(I totally copy fit funtion from UnderBaggingClassifier)

![image](https://user-images.githubusercontent.com/83857592/223703150-089fb6c9-d3e5-4804-9d9a-e233c8d62605.png)

**Comment by ZhiningLiu1998** [comment]
It seems that the `fit_resample` method of your self-defined sampler does not support sampling with `sample_weight`, which is needed for making the `pipeline` work with your sampler.

You can check if your sampler support sampling with `sample_weight` (it should be an array that has the same shape as `y`).
If not, this can be easily implemented by indexing the `sample_weight` (if not `None`) in the same way as you indexing the `X` and `y` with the new resampled index.

PS, you don't have to implement this if you do not plan to support `sample_weight` in your sampler, but you still need to define this keyword argument with a default value = None in the `fit_resample` method, otherwise this line https://github.com/ZhiningLiu1998/imbalanced-ensemble/blob/main/imbens/pipeline.py#L418 wont be able to execute. One simple way to do this is just add the `sample_weight=None` in the parameters, and do
```python
if sample_weight is not None:
    raise NotImplementedError("'sample_weight' is not supported by {yoursamplername}.")
```
