### ISSUE TITLE
Cannot conda env export due to missing comma in  INSTALL_REQUIRES list

### ISSUE THREAD

**Issue by MarcSkovMadsen** [ZhiningLiu1998/imbalanced-ensemble#16]
You have a missing comma in the INSTALL_REQUIRES list which breaks `conda env export`.

![image](https://user-images.githubusercontent.com/42288570/216509809-232163bf-634a-4d6a-8d24-349afd62cbcb.png)

## Context

I'm trying to export my conda environment, but it fails.

```bash
conda env export > environment.yaml

InvalidVersionSpec: Invalid version '1.1.3joblib>=0.11': invalid character(s)
```

After some time digging around I find the cause using the command

```bash
# grep -rl "1.1.3joblib>=0.11" /opt/conda/envs/mt-base
/opt/conda/envs/mt-base/lib/python3.10/site-packages/imbalanced_ensemble-0.1.7.dist-info/METADATA
```

and I end up here :-)

Your package `imbalanced-ensemble` is a dependency of `autoviml` which is in my `environment.yaml` file.

**Comment by ZhiningLiu1998** [comment]
@all-contributors please add @MarcSkovMadsen for reporting and fixing bugs
