### ISSUE TITLE
How to normalize confusion matrix

### ISSUE THREAD

**Issue by marcodelmoral** [ZhiningLiu1998/imbalanced-ensemble#28]
How can I normalize confusion matrix plot?

**Comment by ZhiningLiu1998** [comment]
I'm not sure what you mean by normalizing the confusion matrix, but you may find this helpful:
- [`imbens.visualizer` documentation](https://imbalanced-ensemble.readthedocs.io/en/latest/api/visualizer/_autosummary/imbens.visualizer.ImbalancedEnsembleVisualizer.html)
- [`seaborn.heatmap` documentation](https://seaborn.pydata.org/generated/seaborn.heatmap.html)
