### ISSUE TITLE
Supports the generation of PMML files

### ISSUE THREAD

**Issue by iceicei** [ZhiningLiu1998/imbalanced-ensemble#29]
Hi, IMBENS is a great machine learning library, but I have a problem now, I want to deploy self_paced_ensemble algorithm as online services to production environment, how to generate PMML files successfully. I have tried Nyoka and sklearn2pmml so far, but all failed.

**Comment by ZhiningLiu1998** [comment]
Hi thanks for raising this issue, but unfortunately I'm not an expert in this area. I don't have experience with PMML files thus not planning to add support for this in the near future. I took a glance at the sklearn2pmml reference like this page https://openscoring.io/blog/2023/05/03/converting_sklearn_subclass_pmml/, and it seems that there is a way to convert customized sklearn estimator (like those provided in imbens) by adhering some certain standards, maybe that's something you can try by creating a wrapper class/ write your own estimator with the functions & samplers provided in IMBENS.
