### ISSUE TITLE
可视化集成分类器性能曲线时报错

### ISSUE THREAD

**Issue by huajuanren** [ZhiningLiu1998/imbalanced-ensemble#3]
您好，执行./examples/visualizer/plot_performance_curve.py，出现以下错误，应该怎么解决呢？
![2021-08-20_134006](https://user-images.githubusercontent.com/37321841/130185276-afd817f1-320b-4118-9d0b-a03ead05320b.png)

**Comment by ZhiningLiu1998** [comment]
Hi Huajuan,

我在本地并不能复现你的错误，这段示例代码在我的环境下执行是正常的。

报错可能是seaborn和pandas的版本与我的运行环境不一致造成的，我的环境中这两个package的版本是：
- `pandas v1.2.4`
- `seaborn v0.11.0`

首先，可能需要你提供一下你环境中这两个包的版本（可以用`pip show xxx`命令查看），方便我去定位和解决问题。

之后你可以尝试用下面的命令安装与我一致的软件版本，然后看会不会出现同样的报错。
```
pip install pandas==1.2.4
pip install seaborn==0.11.0
```

Best,
Zhining

**Comment by huajuanren** [comment]
非常感谢，我按照您提供的方法，解决了报错问题。
首先检查了seaborn和pandas版本，seaborn v0.11.2，pandas v1.1.5，
然后安装了v0.11.0的seaborn，重新运行程序，
程序执行成功啦。

**Comment by huajuanren** [comment]
非常感谢，按照您提供的方法，解决了报错问题。


P.S. 在看代码时，在下面文件中注意到了一处笔误。
./imbalanced_ensemble/sampler/under_sampling/_prototype_selection/_self_paced_under_sampler.py
./imbalanced_ensemble/ensemble/under_sampling/self_paced_ensemble.py







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZhiningLiu1998/imbalanced-ensemble"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月21日(星期六) 下午2:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZhiningLiu1998/imbalanced-ensemble] 可视化集成分类器性能曲线时报错 (#3)





 
Hi Huajuan,
 
我在本地并不能复现你的错误，这段示例代码在我的环境下执行是正常的。
 
报错可能是seaborn和pandas的版本与我的运行环境不一致造成的，我的环境中这两个package的版本是：
  
pandas v1.2.4
 
seaborn v0.11.0
  
首先，可能需要你提供一下你环境中这两个包的版本（可以用pip show xxx命令查看），方便我去定位和解决问题。
 
之后你可以尝试用下面的命令安装与我一致的软件版本，然后看会不会出现同样的报错。
 pip install pandas==1.2.4 pip install seaborn==0.11.0  
Best,
 Zhining
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ZhiningLiu1998** [comment]
> 非常感谢，按照您提供的方法，解决了报错问题。 P.S. 在看代码时，在下面文件中注意到了一处笔误。 ./imbalanced_ensemble/sampler/under_sampling/_prototype_selection/_self_paced_under_sampler.py ./imbalanced_ensemble/ensemble/under_sampling/self_paced_ensemble.py
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ZhiningLiu1998/imbalanced-ensemble" ***@***.***&gt;; 发送时间:&nbsp;2021年8月21日(星期六) 下午2:50 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [ZhiningLiu1998/imbalanced-ensemble] 可视化集成分类器性能曲线时报错 (#3) Hi Huajuan, 我在本地并不能复现你的错误，这段示例代码在我的环境下执行是正常的。 报错可能是seaborn和pandas的版本与我的运行环境不一致造成的，我的环境中这两个package的版本是： pandas v1.2.4 seaborn v0.11.0 首先，可能需要你提供一下你环境中这两个包的版本（可以用pip show xxx命令查看），方便我去定位和解决问题。 之后你可以尝试用下面的命令安装与我一致的软件版本，然后看会不会出现同样的报错。 pip install pandas==1.2.4 pip install seaborn==0.11.0 Best, Zhining — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

谢谢，具体在每个文件的第几行？也欢迎你改正后直接提交PR

**Comment by ZhiningLiu1998** [comment]
@all-contributors please add @huajuanren for reporting bugs and typos ~
