### ISSUE TITLE
关于smoteboost的疑问

### ISSUE THREAD

**Issue by nevereverforget1** [ZhiningLiu1998/imbalanced-ensemble#34]
你好你好，
smoteboost原文章的伪代码中在每轮boosting之后都创建N个实例，也就是说每个训练弱分类器的数据集是越来越大的。
[https://www.doc88.com/p-1911929932421.html](url)
但是这里的smoteboost尽管也在每轮boosting之后进行采样，（imbens.ensemble._boost.py的475行），但是实际上只有第一轮boosting起作用，后面便不进行采样因为数据集已经平衡了，那么这个做法和先进行smote再adaboost（即在boosting循环之前采样）是等效的，这就是一个简单拼接的做法。
我不太清楚哪个方法是正确的，希望你能给点建议，太感谢了！

**Comment by nevereverforget1** [comment]
[](https://github.com/ZhiningLiu1998/imbalanced-ensemble/blob/main/imbens/ensemble/_boost.py)

**Comment by nevereverforget1** [comment]
[https://github.com/ZhiningLiu1998/imbalanced-ensemble/blob/main/imbens/ensemble/_boost.py](url)

**Comment by nevereverforget1** [comment]
参数没注意到

**Comment by nevereverforget1** [comment]
参数没注意到

**Comment by ZhiningLiu1998** [comment]
感谢使用，有其他问题也可以再问。
